install:
  # Install Anaconda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -n py3torch-cpu python=3.7 scipy=1.4.1 ipykernel=5.1.4 -y
  # py3.7 for asyncio.WindowsProactorEventLoopPolicy() support
  - conda activate py3torch-cpu
  - conda install pytorch=1.4.0 torchvision=0.5.0 cpuonly=1.0 -c pytorch -y
  # for test
  - pip install sure --yes
 
 
script:
  - conda activate py3torch-cpu
  - cd ./test
  - chmod +x ./run.sh
  - ./run.sh
